[package]
name = "a2048"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.4"
grid = { git = "https://github.com/brecert/grid" }
paste = "1.0.5"
rand = "0.8.4"
crossterm = "0.22.1"
